language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  - docker build -t mitchey/udagram-api-feed:v2023 ./udagram-api-feed
  - docker build -t mitchey/udagram-api-user:v2023 ./udagram-api-user
  - docker build -t mitchey/udagram-frontend:v2023 ./udagram-frontend
  - docker build -t mitchey/reverseproxy:v2023 ./udagram-reverseproxy
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push mitchey/udagram-api-feed:v2023
  - docker push mitchey/udagram-api-user:v2023
  - docker push mitchey/udagram-frontend:v2023
  - docker push mitchey/reverseproxy:v2023
